[build]
builder = "NIXPACKS"
buildCommand = "npm install --production"

[deploy]
startCommand = "node src/app.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
